name: Build and test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - development
      - main
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8.0.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          cache: "maven"

      - name: Build with Maven
        run: mvn -B package --file pom.xml
