name: SonarCloud scan

on:
  pull_request: 
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  sonarcloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - 8.0.x
    
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: List target directory
        run: ls -la
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.java.binaries=target